services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - "5433:5432"
    networks:
      - web

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PRISMA_URL=postgresql://postgres:password@db:5432/portfolio?schema=public
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:password@db:5432/portfolio?schema=public
    networks:
      - web
    depends_on:
      - db

  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - web

networks:
  web:
volumes:
  caddy_data:
  caddy_config:
