-- SUPABASE SETUP (Complete Version)

-- Enable Moddatetime extension
create extension if not exists moddatetime schema extensions;

-- PROJECTS (Admin managed portfolio)

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  link text,                -- Live URL
  "techStack" text[],       -- Array of strings
  "githubUrl" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.projects enable row level security;

-- Public Read
create policy "Allow public read access on projects"
on public.projects for select
to public
using (true);

-- Admin Full Access
create policy "Allow admin full access on projects"
on public.projects for all
to authenticated
using (auth.jwt() ->> 'email' = 'aditya.malik32x@gmail.com')
with check (auth.jwt() ->> 'email' = 'aditya.malik32x@gmail.com');


-- MESSAGES (Contact Form)

create table if not exists public.messages (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

-- Public Insert (Anyone can send a message)
create policy "Allow public insert access on messages"
on public.messages for insert
to public
with check (true);

-- Admin Read/Delete
create policy "Allow admin read access on messages"
on public.messages for select
to authenticated
using (auth.jwt() ->> 'email' = 'aditya.malik32x@gmail.com');

create policy "Allow admin delete access on messages"
on public.messages for delete
to authenticated
using (auth.jwt() ->> 'email' = 'aditya.malik32x@gmail.com');


-- SITE CONTENT (Resume, Config)

create table if not exists public.site_content (
  key text primary key,
  value jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.site_content enable row level security;

-- Public Read
create policy "Allow public read access on site_content"
on public.site_content for select
to public
using (true);

-- Admin Write
create policy "Allow admin write access on site_content"
on public.site_content for all
to authenticated
using (auth.jwt() ->> 'email' = 'aditya.malik32x@gmail.com')
with check (auth.jwt() ->> 'email' = 'aditya.malik32x@gmail.com');


-- FORUM (Threads & Replies/Posts)

-- THREADS
create table if not exists public.threads (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  content text not null,
  image_url text, -- Optional image
  reply_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  bumped_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.threads enable row level security;

create policy "Allow public read threads"
on public.threads for select
to public
using (true);

create policy "Allow public insert threads_anon"
on public.threads for insert
to public
with check (true);

-- POSTS (Replies)
create table if not exists public.posts (
  id uuid default gen_random_uuid() primary key,
  thread_id uuid not null references public.threads(id) on delete cascade,
  content text not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.posts enable row level security;

create policy "Allow public read posts"
on public.posts for select
to public
using (true);

create policy "Allow public insert posts_anon"
on public.posts for insert
to public
with check (true);


-- FUNCTION: Increment Reply Count & Bump

-- Trigger to increment reply_count on new post
create or replace function public.handle_new_post()
returns trigger as $$
begin
  update public.threads
  set 
    reply_count = reply_count + 1,
    bumped_at = now()
  where id = new.thread_id;
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid duplication
drop trigger if exists on_new_post on public.posts;

create trigger on_new_post
after insert on public.posts
for each row execute procedure public.handle_new_post();


-- STORAGE BUCKETS

-- Create bucket for forum uploads if not exists
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do nothing;

create policy "Public Access"
on storage.objects for select
to public
using ( bucket_id = 'uploads' );

create policy "Public Upload"
on storage.objects for insert
to public
with check ( bucket_id = 'uploads' );