import Header from '@/components/Header'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { supabase } from '@/lib/supabaseClient';
// @ts-expect-error: side-effect CSS import has no type declarations
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { data: resumeData, error: resumeError} = await supabase// fetch resume data
    .from('site_content')
    .select('value')
    .eq('key','resume')
    .single();//  cuz only one row

  if( resumeError ){
    console.error("Failed to fetch resume", resumeError.message);
  }

  const resumeUrl = resumeData?.value?.url;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16`}
      >
        <Header resumeUrl={resumeUrl} />
        {children}
      </body>
    </html>
  );
}
